<?php

/**
 * @file
 * Contains custom_tweaks.module
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;
use Drupal\views\Views;

/**
 * Implements hook_help().
 */
function custom_tweaks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_tweaks module.
    case 'help.page.custom_tweaks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Various tweaks, modifications, and enhancements to various frontend and backend features.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function custom_tweaks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array('views_exposed_form__acquia_search__page', $form['#theme'])) {
    $form['search']['#placeholder'] = t('Search');
  }
}

/**
 * Helper function that grabs the content from a view's display(s).
 * @param  string $viewname The machine name of the view.
 * @param  array  $displays An array that lists the machine name of the desired displays.
 * @return string $output   The resulting markup, if any.
 */
function custom_tweaks_views_get_resources($viewname, $displays) {
  $output = '';

  foreach($displays as $display) {
    $view = Views::getView($viewname);
    $view->setDisplay($display);
    $view->execute();

    if ($view->total_rows) {
      $output .= drupal_render($view->render());
    }
  }

  return $output;
}
